/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'activityType' : ActivityType,
  'date' : string,
  'name' : string,
  'description' : string,
}
export type ActivityType = { 'workshop' : null } |
  { 'hackathon' : null } |
  { 'certification' : null } |
  { 'competition' : null } |
  { 'project' : null };
export interface AggregateStats {
  'entrepreneurshipCount' : bigint,
  'totalStudents' : bigint,
  'higherStudiesCount' : bigint,
  'averageCRI' : bigint,
  'placementCount' : bigint,
}
export type AttemptSelfRating = bigint;
export type CareerPathGoal = { 'placement' : null } |
  { 'higherStudies' : null } |
  { 'entrepreneurship' : null };
export type Domain = { 'other' : null } |
  { 'dataScience' : null } |
  { 'research' : null } |
  { 'design' : null } |
  { 'hardware' : null } |
  { 'software' : null } |
  { 'management' : null };
export interface Interest { 'domain' : Domain, 'level' : bigint }
export interface InterviewAttempt {
  'domain' : InterviewDomain,
  'selfRating' : AttemptSelfRating,
  'questionText' : string,
  'answerAttempt' : string,
}
export type InterviewDomain = { 'dataScience' : null } |
  { 'design' : null } |
  { 'software' : null } |
  { 'management' : null };
export interface InterviewQuestion {
  'question' : string,
  'domain' : InterviewDomain,
  'answer' : string,
}
export type ProficiencyLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'expert' : null };
export interface Skill { 'name' : string, 'proficiency' : ProficiencyLevel }
export interface StudentProfile {
  'bio' : string,
  'cri' : bigint,
  'interests' : Array<Interest>,
  'name' : string,
  'year' : bigint,
  'activities' : Array<Activity>,
  'careerPathGoal' : CareerPathGoal,
  'department' : string,
  'skills' : Array<Skill>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInterviewQuestion' : ActorMethod<
    [string, InterviewDomain, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [
      string,
      string,
      bigint,
      CareerPathGoal,
      string,
      Array<Interest>,
      Array<Skill>,
      Array<Activity>,
    ],
    undefined
  >,
  'getAggregateStats' : ActorMethod<[], AggregateStats>,
  'getAllProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyInterviewAttempts' : ActorMethod<[], Array<InterviewAttempt>>,
  'getMyProfile' : ActorMethod<[], StudentProfile>,
  'getProfileByPrincipal' : ActorMethod<[Principal], StudentProfile>,
  'getQuestionsByDomain' : ActorMethod<
    [InterviewDomain],
    Array<InterviewQuestion>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'submitInterviewAttempt' : ActorMethod<
    [string, InterviewDomain, string, AttemptSelfRating],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];