/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InterviewDomain = IDL.Variant({
  'dataScience' : IDL.Null,
  'design' : IDL.Null,
  'software' : IDL.Null,
  'management' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CareerPathGoal = IDL.Variant({
  'placement' : IDL.Null,
  'higherStudies' : IDL.Null,
  'entrepreneurship' : IDL.Null,
});
export const Domain = IDL.Variant({
  'other' : IDL.Null,
  'dataScience' : IDL.Null,
  'research' : IDL.Null,
  'design' : IDL.Null,
  'hardware' : IDL.Null,
  'software' : IDL.Null,
  'management' : IDL.Null,
});
export const Interest = IDL.Record({ 'domain' : Domain, 'level' : IDL.Nat });
export const ProficiencyLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'expert' : IDL.Null,
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'proficiency' : ProficiencyLevel,
});
export const ActivityType = IDL.Variant({
  'workshop' : IDL.Null,
  'hackathon' : IDL.Null,
  'certification' : IDL.Null,
  'competition' : IDL.Null,
  'project' : IDL.Null,
});
export const Activity = IDL.Record({
  'activityType' : ActivityType,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const AggregateStats = IDL.Record({
  'entrepreneurshipCount' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'higherStudiesCount' : IDL.Nat,
  'averageCRI' : IDL.Nat,
  'placementCount' : IDL.Nat,
});
export const StudentProfile = IDL.Record({
  'bio' : IDL.Text,
  'cri' : IDL.Nat,
  'interests' : IDL.Vec(Interest),
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'activities' : IDL.Vec(Activity),
  'careerPathGoal' : CareerPathGoal,
  'department' : IDL.Text,
  'skills' : IDL.Vec(Skill),
});
export const AttemptSelfRating = IDL.Nat;
export const InterviewAttempt = IDL.Record({
  'domain' : InterviewDomain,
  'selfRating' : AttemptSelfRating,
  'questionText' : IDL.Text,
  'answerAttempt' : IDL.Text,
});
export const InterviewQuestion = IDL.Record({
  'question' : IDL.Text,
  'domain' : InterviewDomain,
  'answer' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInterviewQuestion' : IDL.Func(
      [IDL.Text, InterviewDomain, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CareerPathGoal,
        IDL.Text,
        IDL.Vec(Interest),
        IDL.Vec(Skill),
        IDL.Vec(Activity),
      ],
      [],
      [],
    ),
  'getAggregateStats' : IDL.Func([], [AggregateStats], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyInterviewAttempts' : IDL.Func(
      [],
      [IDL.Vec(InterviewAttempt)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [StudentProfile], ['query']),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [StudentProfile],
      ['query'],
    ),
  'getQuestionsByDomain' : IDL.Func(
      [InterviewDomain],
      [IDL.Vec(InterviewQuestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'submitInterviewAttempt' : IDL.Func(
      [IDL.Text, InterviewDomain, IDL.Text, AttemptSelfRating],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InterviewDomain = IDL.Variant({
    'dataScience' : IDL.Null,
    'design' : IDL.Null,
    'software' : IDL.Null,
    'management' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CareerPathGoal = IDL.Variant({
    'placement' : IDL.Null,
    'higherStudies' : IDL.Null,
    'entrepreneurship' : IDL.Null,
  });
  const Domain = IDL.Variant({
    'other' : IDL.Null,
    'dataScience' : IDL.Null,
    'research' : IDL.Null,
    'design' : IDL.Null,
    'hardware' : IDL.Null,
    'software' : IDL.Null,
    'management' : IDL.Null,
  });
  const Interest = IDL.Record({ 'domain' : Domain, 'level' : IDL.Nat });
  const ProficiencyLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'expert' : IDL.Null,
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'proficiency' : ProficiencyLevel,
  });
  const ActivityType = IDL.Variant({
    'workshop' : IDL.Null,
    'hackathon' : IDL.Null,
    'certification' : IDL.Null,
    'competition' : IDL.Null,
    'project' : IDL.Null,
  });
  const Activity = IDL.Record({
    'activityType' : ActivityType,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const AggregateStats = IDL.Record({
    'entrepreneurshipCount' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'higherStudiesCount' : IDL.Nat,
    'averageCRI' : IDL.Nat,
    'placementCount' : IDL.Nat,
  });
  const StudentProfile = IDL.Record({
    'bio' : IDL.Text,
    'cri' : IDL.Nat,
    'interests' : IDL.Vec(Interest),
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'activities' : IDL.Vec(Activity),
    'careerPathGoal' : CareerPathGoal,
    'department' : IDL.Text,
    'skills' : IDL.Vec(Skill),
  });
  const AttemptSelfRating = IDL.Nat;
  const InterviewAttempt = IDL.Record({
    'domain' : InterviewDomain,
    'selfRating' : AttemptSelfRating,
    'questionText' : IDL.Text,
    'answerAttempt' : IDL.Text,
  });
  const InterviewQuestion = IDL.Record({
    'question' : IDL.Text,
    'domain' : InterviewDomain,
    'answer' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInterviewQuestion' : IDL.Func(
        [IDL.Text, InterviewDomain, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CareerPathGoal,
          IDL.Text,
          IDL.Vec(Interest),
          IDL.Vec(Skill),
          IDL.Vec(Activity),
        ],
        [],
        [],
      ),
    'getAggregateStats' : IDL.Func([], [AggregateStats], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyInterviewAttempts' : IDL.Func(
        [],
        [IDL.Vec(InterviewAttempt)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [StudentProfile], ['query']),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [StudentProfile],
        ['query'],
      ),
    'getQuestionsByDomain' : IDL.Func(
        [InterviewDomain],
        [IDL.Vec(InterviewQuestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'submitInterviewAttempt' : IDL.Func(
        [IDL.Text, InterviewDomain, IDL.Text, AttemptSelfRating],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };