/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InterviewQuestion {
    question: string;
    domain: InterviewDomain;
    answer: string;
}
export type AttemptSelfRating = bigint;
export interface InterviewAttempt {
    domain: InterviewDomain;
    selfRating: AttemptSelfRating;
    questionText: string;
    answerAttempt: string;
}
export interface StudentProfile {
    bio: string;
    cri: bigint;
    interests: Array<Interest>;
    name: string;
    year: bigint;
    activities: Array<Activity>;
    careerPathGoal: CareerPathGoal;
    department: string;
    skills: Array<Skill>;
}
export interface Activity {
    activityType: ActivityType;
    date: string;
    name: string;
    description: string;
}
export interface Skill {
    name: string;
    proficiency: ProficiencyLevel;
}
export interface AggregateStats {
    entrepreneurshipCount: bigint;
    totalStudents: bigint;
    higherStudiesCount: bigint;
    averageCRI: bigint;
    placementCount: bigint;
}
export interface Interest {
    domain: Domain;
    level: bigint;
}
export enum ActivityType {
    workshop = "workshop",
    hackathon = "hackathon",
    certification = "certification",
    competition = "competition",
    project = "project"
}
export enum CareerPathGoal {
    placement = "placement",
    higherStudies = "higherStudies",
    entrepreneurship = "entrepreneurship"
}
export enum Domain {
    other = "other",
    dataScience = "dataScience",
    research = "research",
    design = "design",
    hardware = "hardware",
    software = "software",
    management = "management"
}
export enum InterviewDomain {
    dataScience = "dataScience",
    design = "design",
    software = "software",
    management = "management"
}
export enum ProficiencyLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    expert = "expert"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInterviewQuestion(questionText: string, domain: InterviewDomain, answer: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateProfile(name: string, department: string, year: bigint, careerPathGoal: CareerPathGoal, bio: string, interests: Array<Interest>, skills: Array<Skill>, activities: Array<Activity>): Promise<void>;
    getAggregateStats(): Promise<AggregateStats>;
    getAllProfiles(): Promise<Array<StudentProfile>>;
    getCallerUserProfile(): Promise<StudentProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyInterviewAttempts(): Promise<Array<InterviewAttempt>>;
    getMyProfile(): Promise<StudentProfile>;
    getProfileByPrincipal(p: Principal): Promise<StudentProfile>;
    getQuestionsByDomain(domain: InterviewDomain): Promise<Array<InterviewQuestion>>;
    getUserProfile(user: Principal): Promise<StudentProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: StudentProfile): Promise<void>;
    submitInterviewAttempt(questionText: string, domain: InterviewDomain, answerAttempt: string, selfRating: AttemptSelfRating): Promise<void>;
}
import type { Activity as _Activity, ActivityType as _ActivityType, AttemptSelfRating as _AttemptSelfRating, CareerPathGoal as _CareerPathGoal, Domain as _Domain, Interest as _Interest, InterviewAttempt as _InterviewAttempt, InterviewDomain as _InterviewDomain, InterviewQuestion as _InterviewQuestion, ProficiencyLevel as _ProficiencyLevel, Skill as _Skill, StudentProfile as _StudentProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInterviewQuestion(arg0: string, arg1: InterviewDomain, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInterviewQuestion(arg0, to_candid_InterviewDomain_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInterviewQuestion(arg0, to_candid_InterviewDomain_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: string, arg2: bigint, arg3: CareerPathGoal, arg4: string, arg5: Array<Interest>, arg6: Array<Skill>, arg7: Array<Activity>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, to_candid_CareerPathGoal_n5(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_vec_n7(this._uploadFile, this._downloadFile, arg5), to_candid_vec_n12(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n17(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, to_candid_CareerPathGoal_n5(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_vec_n7(this._uploadFile, this._downloadFile, arg5), to_candid_vec_n12(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n17(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async getAggregateStats(): Promise<AggregateStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregateStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregateStats();
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInterviewAttempts(): Promise<Array<InterviewAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInterviewAttempts();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInterviewAttempts();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_StudentProfile_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_StudentProfile_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByPrincipal(arg0: Principal): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByPrincipal(arg0);
                return from_candid_StudentProfile_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByPrincipal(arg0);
            return from_candid_StudentProfile_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByDomain(arg0: InterviewDomain): Promise<Array<InterviewQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByDomain(to_candid_InterviewDomain_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByDomain(to_candid_InterviewDomain_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_StudentProfile_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_StudentProfile_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitInterviewAttempt(arg0: string, arg1: InterviewDomain, arg2: string, arg3: AttemptSelfRating): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInterviewAttempt(arg0, to_candid_InterviewDomain_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInterviewAttempt(arg0, to_candid_InterviewDomain_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
}
function from_candid_ActivityType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_CareerPathGoal_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CareerPathGoal): CareerPathGoal {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Domain_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Domain): Domain {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Interest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interest): Interest {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewAttempt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewAttempt): InterviewAttempt {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewDomain_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewDomain): InterviewDomain {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewQuestion_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewQuestion): InterviewQuestion {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ProficiencyLevel_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProficiencyLevel): ProficiencyLevel {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : from_candid_StudentProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    cri: bigint;
    interests: Array<_Interest>;
    name: string;
    year: bigint;
    activities: Array<_Activity>;
    careerPathGoal: _CareerPathGoal;
    department: string;
    skills: Array<_Skill>;
}): {
    bio: string;
    cri: bigint;
    interests: Array<Interest>;
    name: string;
    year: bigint;
    activities: Array<Activity>;
    careerPathGoal: CareerPathGoal;
    department: string;
    skills: Array<Skill>;
} {
    return {
        bio: value.bio,
        cri: value.cri,
        interests: from_candid_vec_n25(_uploadFile, _downloadFile, value.interests),
        name: value.name,
        year: value.year,
        activities: from_candid_vec_n30(_uploadFile, _downloadFile, value.activities),
        careerPathGoal: from_candid_CareerPathGoal_n35(_uploadFile, _downloadFile, value.careerPathGoal),
        department: value.department,
        skills: from_candid_vec_n37(_uploadFile, _downloadFile, value.skills)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domain: _Domain;
    level: bigint;
}): {
    domain: Domain;
    level: bigint;
} {
    return {
        domain: from_candid_Domain_n28(_uploadFile, _downloadFile, value.domain),
        level: value.level
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityType: _ActivityType;
    date: string;
    name: string;
    description: string;
}): {
    activityType: ActivityType;
    date: string;
    name: string;
    description: string;
} {
    return {
        activityType: from_candid_ActivityType_n33(_uploadFile, _downloadFile, value.activityType),
        date: value.date,
        name: value.name,
        description: value.description
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    proficiency: _ProficiencyLevel;
}): {
    name: string;
    proficiency: ProficiencyLevel;
} {
    return {
        name: value.name,
        proficiency: from_candid_ProficiencyLevel_n40(_uploadFile, _downloadFile, value.proficiency)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domain: _InterviewDomain;
    selfRating: _AttemptSelfRating;
    questionText: string;
    answerAttempt: string;
}): {
    domain: InterviewDomain;
    selfRating: AttemptSelfRating;
    questionText: string;
    answerAttempt: string;
} {
    return {
        domain: from_candid_InterviewDomain_n48(_uploadFile, _downloadFile, value.domain),
        selfRating: value.selfRating,
        questionText: value.questionText,
        answerAttempt: value.answerAttempt
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: string;
    domain: _InterviewDomain;
    answer: string;
}): {
    question: string;
    domain: InterviewDomain;
    answer: string;
} {
    return {
        question: value.question,
        domain: from_candid_InterviewDomain_n48(_uploadFile, _downloadFile, value.domain),
        answer: value.answer
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    dataScience: null;
} | {
    research: null;
} | {
    design: null;
} | {
    hardware: null;
} | {
    software: null;
} | {
    management: null;
}): Domain {
    return "other" in value ? Domain.other : "dataScience" in value ? Domain.dataScience : "research" in value ? Domain.research : "design" in value ? Domain.design : "hardware" in value ? Domain.hardware : "software" in value ? Domain.software : "management" in value ? Domain.management : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workshop: null;
} | {
    hackathon: null;
} | {
    certification: null;
} | {
    competition: null;
} | {
    project: null;
}): ActivityType {
    return "workshop" in value ? ActivityType.workshop : "hackathon" in value ? ActivityType.hackathon : "certification" in value ? ActivityType.certification : "competition" in value ? ActivityType.competition : "project" in value ? ActivityType.project : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placement: null;
} | {
    higherStudies: null;
} | {
    entrepreneurship: null;
}): CareerPathGoal {
    return "placement" in value ? CareerPathGoal.placement : "higherStudies" in value ? CareerPathGoal.higherStudies : "entrepreneurship" in value ? CareerPathGoal.entrepreneurship : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
}): ProficiencyLevel {
    return "intermediate" in value ? ProficiencyLevel.intermediate : "beginner" in value ? ProficiencyLevel.beginner : "advanced" in value ? ProficiencyLevel.advanced : "expert" in value ? ProficiencyLevel.expert : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dataScience: null;
} | {
    design: null;
} | {
    software: null;
} | {
    management: null;
}): InterviewDomain {
    return "dataScience" in value ? InterviewDomain.dataScience : "design" in value ? InterviewDomain.design : "software" in value ? InterviewDomain.software : "management" in value ? InterviewDomain.management : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentProfile>): Array<StudentProfile> {
    return value.map((x)=>from_candid_StudentProfile_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interest>): Array<Interest> {
    return value.map((x)=>from_candid_Interest_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InterviewAttempt>): Array<InterviewAttempt> {
    return value.map((x)=>from_candid_InterviewAttempt_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InterviewQuestion>): Array<InterviewQuestion> {
    return value.map((x)=>from_candid_InterviewQuestion_n51(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Activity_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Activity): _Activity {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_CareerPathGoal_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerPathGoal): _CareerPathGoal {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Domain_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Domain): _Domain {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Interest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interest): _Interest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewDomain_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewDomain): _InterviewDomain {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProficiencyLevel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProficiencyLevel): _ProficiencyLevel {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Skill_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): _Skill {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_StudentProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): _StudentProfile {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    proficiency: ProficiencyLevel;
}): {
    name: string;
    proficiency: _ProficiencyLevel;
} {
    return {
        name: value.name,
        proficiency: to_candid_ProficiencyLevel_n15(_uploadFile, _downloadFile, value.proficiency)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityType: ActivityType;
    date: string;
    name: string;
    description: string;
}): {
    activityType: _ActivityType;
    date: string;
    name: string;
    description: string;
} {
    return {
        activityType: to_candid_ActivityType_n20(_uploadFile, _downloadFile, value.activityType),
        date: value.date,
        name: value.name,
        description: value.description
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    cri: bigint;
    interests: Array<Interest>;
    name: string;
    year: bigint;
    activities: Array<Activity>;
    careerPathGoal: CareerPathGoal;
    department: string;
    skills: Array<Skill>;
}): {
    bio: string;
    cri: bigint;
    interests: Array<_Interest>;
    name: string;
    year: bigint;
    activities: Array<_Activity>;
    careerPathGoal: _CareerPathGoal;
    department: string;
    skills: Array<_Skill>;
} {
    return {
        bio: value.bio,
        cri: value.cri,
        interests: to_candid_vec_n7(_uploadFile, _downloadFile, value.interests),
        name: value.name,
        year: value.year,
        activities: to_candid_vec_n17(_uploadFile, _downloadFile, value.activities),
        careerPathGoal: to_candid_CareerPathGoal_n5(_uploadFile, _downloadFile, value.careerPathGoal),
        department: value.department,
        skills: to_candid_vec_n12(_uploadFile, _downloadFile, value.skills)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domain: Domain;
    level: bigint;
}): {
    domain: _Domain;
    level: bigint;
} {
    return {
        domain: to_candid_Domain_n10(_uploadFile, _downloadFile, value.domain),
        level: value.level
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Domain): {
    other: null;
} | {
    dataScience: null;
} | {
    research: null;
} | {
    design: null;
} | {
    hardware: null;
} | {
    software: null;
} | {
    management: null;
} {
    return value == Domain.other ? {
        other: null
    } : value == Domain.dataScience ? {
        dataScience: null
    } : value == Domain.research ? {
        research: null
    } : value == Domain.design ? {
        design: null
    } : value == Domain.hardware ? {
        hardware: null
    } : value == Domain.software ? {
        software: null
    } : value == Domain.management ? {
        management: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProficiencyLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
} {
    return value == ProficiencyLevel.intermediate ? {
        intermediate: null
    } : value == ProficiencyLevel.beginner ? {
        beginner: null
    } : value == ProficiencyLevel.advanced ? {
        advanced: null
    } : value == ProficiencyLevel.expert ? {
        expert: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewDomain): {
    dataScience: null;
} | {
    design: null;
} | {
    software: null;
} | {
    management: null;
} {
    return value == InterviewDomain.dataScience ? {
        dataScience: null
    } : value == InterviewDomain.design ? {
        design: null
    } : value == InterviewDomain.software ? {
        software: null
    } : value == InterviewDomain.management ? {
        management: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    workshop: null;
} | {
    hackathon: null;
} | {
    certification: null;
} | {
    competition: null;
} | {
    project: null;
} {
    return value == ActivityType.workshop ? {
        workshop: null
    } : value == ActivityType.hackathon ? {
        hackathon: null
    } : value == ActivityType.certification ? {
        certification: null
    } : value == ActivityType.competition ? {
        competition: null
    } : value == ActivityType.project ? {
        project: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerPathGoal): {
    placement: null;
} | {
    higherStudies: null;
} | {
    entrepreneurship: null;
} {
    return value == CareerPathGoal.placement ? {
        placement: null
    } : value == CareerPathGoal.higherStudies ? {
        higherStudies: null
    } : value == CareerPathGoal.entrepreneurship ? {
        entrepreneurship: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Skill>): Array<_Skill> {
    return value.map((x)=>to_candid_Skill_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Activity>): Array<_Activity> {
    return value.map((x)=>to_candid_Activity_n18(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Interest>): Array<_Interest> {
    return value.map((x)=>to_candid_Interest_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
